import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "How Modu Tools handles local storage, optional cookies, analytics, advertising, and external data requests.",
  alternates: { canonical: "/en/privacy", languages: { en: "/en/privacy", ko: "/privacy", "x-default": "/privacy" } },
};

export default function EnglishPrivacyPage() {
  return (
    <article className="mx-auto max-w-3xl px-5 py-12 text-[#6e5a50]">
      <p className="text-sm font-black uppercase tracking-[0.14em] text-[#a93d28]">Updated September 8, 2026</p>
      <h1 className="mt-2 text-4xl font-black tracking-tight text-[#271f1b]">Privacy policy</h1>
      <div className="mt-8 space-y-8 leading-7">
        <section><h2 className="mb-2 text-xl font-black text-[#3f3029]">1. Operator and scope</h2><p>Modu Tools operator imhyuk98 does not create member accounts or user profiles. Unless a tool says otherwise, calculator, text, and image inputs are processed in the browser and are not sent to or stored in an operator database.</p></section>
        <section><h2 className="mb-2 text-xl font-black text-[#3f3029]">2. Browser storage</h2><p>Local storage keeps favorites, recent tools, game records, return streaks, and the optional-cookie choice. It remains in that browser until you remove the site data.</p></section>
        <section><h2 className="mb-2 text-xl font-black text-[#3f3029]">3. Optional analytics</h2><p>Google Analytics loads only after “Allow optional cookies.” Page paths and titles, tool start, completion and share events, browser and device type, approximate region, language, visit time, and a cookie-based client identifier may be processed to understand usage and improve reliability. Query strings and hashes are removed from analytics page locations, and tool inputs are not sent as analytics parameters.</p></section>
        <section><h2 className="mb-2 text-xl font-black text-[#3f3029]">4. Retention and deletion</h2><p>Browser data remains until you delete it. Google Analytics event-level data is operated with a retention setting of no more than 14 months before automatic deletion; non-identifying aggregate reports may remain longer. Choosing “Essential only” under “Cookie choices” stops future analytics events and attempts to remove this site’s <code>_ga</code> cookies.</p></section>
        <section><h2 className="mb-2 text-xl font-black text-[#3f3029]">5. International processing</h2><p>After analytics consent, the information above may be transmitted over the network to Google LLC and processed in the United States or other countries where Google infrastructure operates for analytics and service operation. Transfers occur while using the site after consent and follow the retention period above. See the <a href="https://policies.google.com/privacy?hl=en" target="_blank" rel="noreferrer" className="font-black underline">Google Privacy Policy</a>.</p></section>
        <section><h2 className="mb-2 text-xl font-black text-[#3f3029]">6. Advertising</h2><p>If Google AdSense is configured, ad scripts and units load only after optional-cookie consent. Google may process cookies, device identifiers, and connection information. Personalized advertising will not be offered in regions requiring a certified consent platform until that process is available.</p></section>
        <section><h2 className="mb-2 text-xl font-black text-[#3f3029]">7. External requests and shared links</h2><p>Exchange-rate lookups, Kakao Maps, external image previews, and source links may disclose an IP address and browser information to those services. A telepathy invitation places names and answers in its shared URL rather than a database, so recipients and browser history may reveal them. Do not enter sensitive information.</p></section>
        <section><h2 className="mb-2 text-xl font-black text-[#3f3029]">8. Choices and contact</h2><p>You can withdraw optional analytics consent and delete browser data and cookies at any time. The operator has no member database for account-level access or correction requests. Use the <a href="https://github.com/imhyuk98/modu-dogu/issues/new" target="_blank" rel="noreferrer" className="font-black underline">public issue form</a> only for questions containing no personal data. For a privacy exposure or security incident that requires a private report, use <a href="https://github.com/imhyuk98/modu-dogu/security/advisories/new" target="_blank" rel="noreferrer" className="font-black underline">private vulnerability reporting</a>.</p></section>
        <section><h2 className="mb-2 text-xl font-black text-[#3f3029]">9. Friend question inboxes</h2><p>New friendship quizzes, chemistry tests, friend manuals and compliment cards require a separate storage agreement before creation or submission. Nicknames, game type, selected answers, random request IDs and creation/submission/expiry times are stored using Cloudflare, Inc. Workers and D1 infrastructure, which may process data outside your country. Replies are visible to the creator. Nicknames are not verified identities. Do not enter sensitive information.</p><p className="mt-3">An inbox accepts up to 100 replies and expires 30 days after creation. Access stops at expiry; hourly cleanup removes expired data from the live database. Creators can delete the entire inbox earlier. Cloudflare recovery backups may retain history for an additional 7–30 days depending on the plan; see <a href="https://developers.cloudflare.com/d1/reference/time-travel/" target="_blank" rel="noreferrer" className="font-black underline">its backup policy</a>. Storage agreement is separate from optional analytics consent.</p><p className="mt-3">The private owner capability is kept in local storage and the owner URL; only its hash is stored in the database. Anyone holding that URL can view and delete all replies. Keep it private. Losing both the URL and browser data has no user recovery option. Request limiting temporarily processes connection information; the application database stores no IP addresses. Infrastructure security processing follows Cloudflare policies. Input values and owner keys are not sent as analytics events. Already-shared result URLs can contain nicknames and answers; deleting the inbox cannot recall copies. Ask the creator or use the private contact channel above for deletion requests. Never post private owner URLs in public issues.</p></section>
        <section><h2 className="mb-2 text-xl font-black text-[#3f3029]">10. Changes</h2><p>Changes to processed information or external services will be posted here with a revised date before they take effect. Material changes will also be announced in the site interface.</p></section>
      </div>
    </article>
  );
}
